config/routes.rb
Fia::Application.routes.draw do
  
  resources :resources, :constraints => { :oid => /[\w+\.]+/ }

    
  namespace :admin do
    resources :resources
  end
  
  get 'oid/:oid' => 'resources#findbyoid' #, :constraints => { :oid => /[\w+\.]+/ } REMOVING THIS BECAUSE IT CONFLICTS WITH JSON
  
  
  get '/admin/', to: 'admin/resources#index'
  get '/admin/new', to: 'admin/resources#new'
  
  root 'resources#index'

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  
  scope :oidTest, -> (oid) { where oid: oid }
  scope :urlTest, -> (retrievalurl) { where retrievalURL: retrievalurl }
  scope :objectTypeTest, -> (objecttype) {where('"objectType"=? OR "objectType"=?', objecttype, 'any')}
  scope :langTypeTest, -> (lang) { where('lang=? OR lang=?', 'any', lang) }
  scope :eventTypeTest, -> (eventtype) {where('"eventType"=? OR "eventType"=?', eventtype, 'any')}
  #scope :search, -> (search) {where description: search}
  scope :searchDescription, -> (search) { where("description LIKE ?", "%#{search}%".downcase)}
  scope :isActive, -> () { where activeTo: '9999-12-31'}
  
  # scope :status, -> (status) { where status: status }
  #   scope :location, -> (location_id) { where location_id: location_id }
  #   scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
  
  def self.findbyoid(params)
    Resource.find_by(oid: params)
  end
  
  def self.find_all_by_name(name)
    find(:all, :conditions => ["LOWER(name) = ?", name.downcase])
  end
  
  private
  
  # def self.search(params)
  #   # Resource.where(oid: params[:oid]) if params.has_key?(:oid)
  #   # Resource.where(objecttype: params[:objecttype]) if params.has_key?(:objecttype)
  #   # 
  #   # Resource.order(:oid)
  #   
  #   scope :status
  # end
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController
  
  def index
    @assets = Asset.all
  end
  
  def edit
    @asset = Asset.find(params[:id])
  end

  def show
    @asset = Asset.find(params[:id])
  end
  
  def update
    @asset = Asset.find(params[:id])
    
    if @asset.update(asset_params)
      redirect_to @asset
    else
      render 'edit'
    end
  end
  
  def new
    @asset = Asset.new
  end
  
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
      
    redirect_to assets_path
  end
  
  private
    def asset_params
      params.require(:asset).permit(:title, :text)
    end
end

app/controllers/admin/resources_controller.rb
class Admin::ResourcesController < ApplicationController
  
  def index
    @assets = Resource.all
  end
  
  def edit
    @asset = Resource.find(params[:id])
  end

  def show
    @asset = Resource.find(params[:id])
  end
  
  def update
    @asset = Resource.find(params[:id])
    
    if @asset.update(asset_params)
      redirect_to @asset
    else
      render 'edit'
    end
  end
  
  def new
    @asset = Resource.new
  end
  
  def destroy
    @asset = Resource.find(params[:id])
    @asset.destroy
      
    redirect_to resources_path
  end
  
  private
    def asset_params
      params.require(:asset).permit(:title, :text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  respond_to :xml,:json
  #before_action :set_asset, only: [:show, :edit, :update, :destroy]
  
  def index
    @assets = Resource.where(nil)
    @assets = @assets.oidTest(params[:oid]) if params[:oid].present?
    @assets = @assets.urlTest(params[:retrievalurl]) if params[:retrievalurl].present?
    @assets = @assets.objectTypeTest(params[:objecttype]) if params[:objecttype].present?
    @assets = @assets.eventTypeTest(params[:eventtype]) if params[:eventtype].present?
    @assets = @assets.langTypeTest(params[:lang]) if params[:lang].present?
    @assets = @assets.searchDescription(params[:search]) if params[:search].present?
    @assets = @assets.isActive() unless params[:showinactive] == 'true'
    
    respond_to do |format|
      format.html { render :xml => @assets }# index.html.erb
      format.xml { render :xml => @assets }# index.xml.builder
      format.json { render :json => @assets }# index.xml.builder
    end
  end
  
  def findbyoid
    @asset = Resource.findbyoid(params[:oid])
    
    respond_to do |format|
      format.html { render :xml => @asset }# index.html.erb
      format.xml { render :xml => @asset }# index.xml.builder
      format.json { render :json => @asset }# index.xml.builder
    end
  end
  
  # GET /resources/1
  # GET /resources/1.json
  def show
    @asset = Resource.find(params[:id])
    
    respond_to do |format|
      format.html { render :xml => @asset }# index.html.erb
      format.xml { render :xml => @asset }# index.xml.builder
      format.json { render :json => @asset }# index.xml.builder
    end
  end
  
  def display
    conditions = []
    conditions << [ "in_production = ?", params[:in_production] ] if params[:in_production].present?
    conditions << [ "year = ?", params[:year] ] if params[:year].present?
    conditions << [ "make = ?", params[:make] ] if params[:make].present?
    @cars = Car.all(:conditions => conditions )
  end

  # GET /assets/new
  # def new
  #   #@asset = Asset.new
  # end

  # GET /assets/1/edit
  def edit
    redirect_to "/"
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Resource.new(resource_params)
    
    if @asset.save
      redirect_to admin_resource_path(@asset), notice: 'Resource was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    @asset = Resource.find(params[:id])
    if @asset.update(resource_params)
      redirect_to admin_resource_path(@asset), notice: 'Resource was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Resource.find(params[:id])
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to admin_resources_path }
      format.json { head :no_content }
    end
  end

  private
  
    def conditions

      c = Array.new
      c << [ "oid = ?", params[:oid] ] if params[:oid].present?
      c << [ "year = ?", params[:year] ] if params[:year].present?
      c << [ "make = ?", params[:make] ] if params[:make].present?
      
      return c
    end
    
    #NOPE WRONG-O
    # def conditions2 
    #       
    #       allowedKeys = [
    #         "oid",
    #         "objecttype"
    #       ]
    #       
    #       conditions = ['']
    #     
    #       #conditionalKeys = ""
    #       
    #       conditionalValues = []
    #       
    #       customParams = params.clone
    #       
    #       customParams.delete("controller")
    #       
    #       customParams.delete("action")
    #       
    #       downCounter = customParams.length
    #       
    #       upCounter = 0
    #       
    #       params.each do |key,value|
    #         
    #         if allowedKeys.include? key
    #           
    #           #Put the 
    #           downCounter -= 1
    #           conditions[0] << key + "=? "
    #           conditions[0] << "AND " if downCounter > 0
    #           
    #           #Populate 
    #           upCounter + -1
    #           conditions << value
    #         end
    #       end
    #       
    #       return conditions
    #       
    #       return ["oid=? AND objecttype=?", "45", "warningText"]
    #     end
    
    def resource_params
      params.require(:resource).permit(:oid, :retrievalURL, :activeFrom, :activeTo, :objectType, :eventType, :description, :lang, :license, :length, :mimeType, :contributorName, :contributorEmail, :useConstraints)
    end
end

app/helpers/admin/assets_helper.rb
module Admin::AssetsHelper
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/admin/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <thead>
    <tr>
      <th>Oid</th>
      <th>Retrievalurl</th>
      <th>Activefrom</th>
      <th>Activeto</th>
      <th>Objecttype</th>
      <th>Eventtype</th>
      <th>Description</th>
      <th>Lang</th>
      <th>License</th>
      <th>Length</th>
      <th>Mimetype</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.oid %></td>
        <td><%= asset.retrievalURL %></td>
        <td><%= asset.activeFrom %></td>
        <td><%= asset.activeTo %></td>
        <td><%= asset.objectType %></td>
        <td><%= asset.eventType %></td>
        <td><%= asset.description %></td>
        <td><%= asset.lang %></td>
        <td><%= asset.license %></td>
        <td><%= asset.length %></td>
        <td><%= asset.mimeType %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/admin/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oid:</strong>
  <%= @asset.oid %>
</p>

<p>
  <strong>Retrievalurl:</strong>
  <%= @asset.retrievalURL %>
</p>

<p>
  <strong>Activefrom:</strong>
  <%= @asset.activeFrom %>
</p>

<p>
  <strong>Activeto:</strong>
  <%= @asset.activeTo %>
</p>

<p>
  <strong>Objecttype:</strong>
  <%= @asset.objectType %>
</p>

<p>
  <strong>Eventtype:</strong>
  <%= @asset.eventType %>
</p>

<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @asset.lang %>
</p>

<p>
  <strong>License:</strong>
  <%= @asset.license %>
</p>

<p>
  <strong>Length:</strong>
  <%= @asset.length %>
</p>

<p>
  <strong>Mimetype:</strong>
  <%= @asset.mimeType %>
</p>

<%= link_to 'Edit', edit_admin_asset_path(@asset) %> |
<%= link_to 'Back', admin_assets_path %>

app/views/admin/resources/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :oid %><br>
    <%= f.text_field :oid, :placeholder => '0.00.0.00000', :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :retrievalURL %><br>
    <%= f.text_field :retrievalURL, :type => "url", :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :activeFrom %><br>
    <%= f.date_select :activeFrom, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :activeTo %><br>
    <%= f.date_select :activeTo, :default => Date.new(9999, 12, 31), :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :objectType %><br>
    <%= f.text_field :objectType, :placeholder => 'e.g. warningText, warningTone', :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :eventType %><br>
    <%= f.text_field :eventType, :value => 'any', :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :size => "90x6", :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :lang %><br>
    <%= f.text_field :lang, :value => 'en', :size => 2, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :license %><br>
    <%= f.text_field :license, :value => 'https://creativecommons.org/licenses/by-sa/4.0/', :type => "url", :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :length %><br>
    <%= f.number_field :length, :type => 'number', :class => 'form-control' %>
		<span>bytes</span>
  </div>
  <div class="field form-group">
    <%= f.label :mimeType %><br>
    <%= f.text_field :mimeType, :placeholder => 'image/svg', :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label "Contributor Name" %><br>
    <%= f.text_field :contributorName, :class => 'form-control' %>
  </div>
	<div class="field form-group">
    <%= f.label "Contributor Email" %><br>
    <%= f.text_field :contributorEmail, :type => 'email', :class => 'form-control' %>
  </div>
	<div class="field form-group">
    <%= f.label "Use Constraints" %><br>
    <%= f.text_field :useConstraints, :value => 'none', :class => 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit 'Update', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/resources/edit.html.erb
<div class="admin">
	<h1>Edit Resource</h1>
	<div class="form-card">
		<%= render 'form' %>
	</div>
	<%= link_to 'List', admin_resources_path, :class => 'glyphicon glyphicon-list back-btn' %>
</div>

app/views/admin/resources/index.html.erb
<div class="admin">
  <% @assets.order("oid desc").each do |asset| %>
	<div class="asset">
		<p class="oid"><%= asset.oid %></p>
		<p class="description"><%= asset.description %></p>
		
		<ul class="use-metadata">
			<li><label>Event Type:</label> <%= asset.eventType %></li>
			<li><label>Object Type: </label> <%= asset.objectType %></li>
			<li><label>Active: </label> <%= asset.activeFrom %>...<%= asset.activeTo %></li>
			<li><label>Contributor: </label> <%= asset.contributorName %> / <a href="<%= asset.contributorEmail %>"><%= asset.contributorEmail %></a></li>
			<li><label>Use Constraints: </label> <%= asset.useConstraints %></li>
		</ul>
		<div class="file">
			<ul class="file-info">
				<li><label>URL: </label> <a class="retrieve" href="<%= asset.retrievalURL %>" target="_blank"><%= asset.retrievalURL %></a></strong></li>
				<li><label>Language: </label> <%= asset.lang %></li>
				<li><label>MIME type: </label> <%= asset.mimeType %></li>
				<li><label>Size: </label> <%= number_to_human_size(asset.length, precision: 2) %></li>
				<li><label>Licence: </label> <a class="retrieve" href="<%= asset.license %>" target="_blank"><%= asset.license %></a></li>
			</ul>
		</div>
		<ul class="edit-actions">
			<li><%= link_to '', admin_resource_path(asset), :class => 'glyphicon glyphicon-share-alt' %></li>
			<li><%= link_to '', edit_admin_resource_path(asset), :class => 'glyphicon glyphicon-pencil' %></li>
			<li><%= link_to '', asset, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'glyphicon glyphicon-trash' %></li>
		</ul>
	</div>
	<% end %>
	<footer>
		<%= link_to 'Add', new_admin_resource_path, :class => 'glyphicon glyphicon-edit' %>
	</footer>
</div>

app/views/admin/resources/new.html.erb
<div class="admin">
	<h1>New Resource</h1>
	<div class="form-card">
		<%= render 'form' %>
	</div>
	<%= link_to 'List', admin_resources_path, :class => 'glyphicon glyphicon-list back-btn' %>
</div>

app/views/admin/resources/show.html.erb
<div class="admin">
	<h1>Resource End Point</h1>
	<div class="form-card">
		<p id="notice"><%= notice %></p>

			<p>
			  <strong>Oid:</strong>
			  <%= @asset.oid %>
			</p>

			<p>
			  <strong>Retrievalurl:</strong>
			  <%= @asset.retrievalURL %>
			</p>

			<p>
			  <strong>Activefrom:</strong>
			  <%= @asset.activeFrom %>
			</p>

			<p>
			  <strong>Activeto:</strong>
			  <%= @asset.activeTo %>
			</p>

			<p>
			  <strong>Objecttype:</strong>
			  <%= @asset.objectType %>
			</p>

			<p>
			  <strong>Eventtype:</strong>
			  <%= @asset.eventType %>
			</p>

			<p>
			  <strong>Description:</strong>
			  <%= @asset.description %>
			</p>

			<p>
			  <strong>Lang:</strong>
			  <%= @asset.lang %>
			</p>

			<p>
			  <strong>License:</strong>
			  <%= @asset.license %>
			</p>

			<p>
			  <strong>Length:</strong>
			  <%= @asset.length %>
			</p>

			<p>
			  <strong>Mimetype:</strong>
			  <%= @asset.mimeType %>
			</p>

			<p>
			  <strong>Contributor Name:</strong>
			  <%= @asset.contributorName %>
			</p>
			

			<p>
			  <strong>Contributor Email:</strong>
			  <%= @asset.contributorEmail %>
			</p>
		
			<p>
			  <strong>Use Constraints:</strong>
			  <%= @asset.useConstraints %>
			</p>
		</div>
		<div class="buttons-container">
			<%= link_to 'List', admin_resources_path, :class => 'glyphicon glyphicon-list back-btn' %>
			<%= link_to 'Edit', edit_admin_resource_path(@asset), :class => 'glyphicon glyphicon-pencil back-btn' %>
		</div>
	</div>
	

<%= link_to 'Back', admin_resource_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <thead>
    <tr>
      <th>Oid</th>
      <th>Retrievalurl</th>
      <th>Activefrom</th>
      <th>Activeto</th>
      <th>Objecttype</th>
      <th>Eventtype</th>
      <th>Description</th>
      <th>Lang</th>
      <th>License</th>
      <th>Length</th>
      <th>Mimetype</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.oid %></td>
        <td><%= asset.retrievalURL %></td>
        <td><%= asset.activeFrom %></td>
        <td><%= asset.activeTo %></td>
        <td><%= asset.objectType %></td>
        <td><%= asset.eventType %></td>
        <td><%= asset.description %></td>
        <td><%= asset.lang %></td>
        <td><%= asset.license %></td>
        <td><%= asset.length %></td>
        <td><%= asset.mimeType %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oid:</strong>
  <%= @asset.oid %>
</p>

<p>
  <strong>Retrievalurl:</strong>
  <%= @asset.retrievalURL %>
</p>

<p>
  <strong>Activefrom:</strong>
  <%= @asset.activeFrom %>
</p>

<p>
  <strong>Activeto:</strong>
  <%= @asset.activeTo %>
</p>

<p>
  <strong>Objecttype:</strong>
  <%= @asset.objectType %>
</p>

<p>
  <strong>Eventtype:</strong>
  <%= @asset.eventType %>
</p>

<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @asset.lang %>
</p>

<p>
  <strong>License:</strong>
  <%= @asset.license %>
</p>

<p>
  <strong>Length:</strong>
  <%= @asset.length %>
</p>

<p>
  <strong>Mimetype:</strong>
  <%= @asset.mimeType %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fia</title>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/index.html.erb
<table>
  <thead>
    <tr>
      <th>Oid</th>
      <th>Retrievalurl</th>
      <th>Activefrom</th>
      <th>Activeto</th>
      <th>Objecttype</th>
      <th>Eventtype</th>
      <th>Description</th>
      <th>Lang</th>
      <th>License</th>
      <th>Length</th>
      <th>Mimetype</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.oid %></td>
        <td><%= asset.retrievalURL %></td>
        <td><%= asset.activeFrom %></td>
        <td><%= asset.activeTo %></td>
        <td><%= asset.objectType %></td>
        <td><%= asset.eventType %></td>
        <td><%= asset.description %></td>
        <td><%= asset.lang %></td>
        <td><%= asset.license %></td>
        <td><%= asset.length %></td>
        <td><%= asset.mimeType %></td>
        <td><%= link_to 'Show', asset %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oid:</strong>
  <%= @asset.oid %>
</p>

<p>
  <strong>Retrievalurl:</strong>
  <%= @asset.retrievalURL %>
</p>

<p>
  <strong>Activefrom:</strong>
  <%= @asset.activeFrom %>
</p>

<p>
  <strong>Activeto:</strong>
  <%= @asset.activeTo %>
</p>

<p>
  <strong>Objecttype:</strong>
  <%= @asset.objectType %>
</p>

<p>
  <strong>Eventtype:</strong>
  <%= @asset.eventType %>
</p>

<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @asset.lang %>
</p>

<p>
  <strong>License:</strong>
  <%= @asset.license %>
</p>

<p>
  <strong>Length:</strong>
  <%= @asset.length %>
</p>

<p>
  <strong>Mimetype:</strong>
  <%= @asset.mimeType %>
</p>